version: "2.2"

services:
  cspmaster:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/csplmc:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspmaster
    depends_on:
      - databaseds
      - cbfmaster
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
             /venv/bin/python /app/csplmc/CspMaster/CspMaster/CspMaster.py 01"

  cspsubarray:
    image: ${DOCKER_REGISTRY_HOST}/ska-docker/csplmc:latest
    depends_on:
      - databaseds
      - cspmaster
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspsubarray
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp/elt/master 10 &&\
             /venv/bin/python /app/csplmc/CspSubarray/CspSubarray/CspSubarray.py 01"
