#
# Docker compose file for setting up SDP devices in CI environment.
# The current setup provides one container each for SDP Master and SDP Subarray device.
# Defines:
#   - sdpmaster: SDP Master device service
#   - sdpsubarray: SDP Subarray device service
# Requires:
#   - tango-docker-compose.yml

version: "2.2"

services:
  sdpmaster:
    image: ${DOCKER_REGISTRY_HOST}/sdp-prototype/tangods_sdp_master:latest
    container_name: ${CONTAINER_NAME_PREFIX}sdp_master
    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    stdin_open: true
    entrypoint: ["python", "SDPMaster"]
    command: ["1", "-v4"]

  sdpsubarray:
    image: ${DOCKER_REGISTRY_HOST}/sdp-prototype/tangods_sdp_subarray:latest
    container_name: ${CONTAINER_NAME_PREFIX}sdp_subarray
    network_mode: ${NETWORK_MODE}
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    stdin_open: true
    entrypoint: ["python", "SDPSubarray"]
    command: ["1", "-v4"]
