#
# Docker compose file for TANGO example device from https://github.com/ska-telescope/tango-example
#
# Defines:
#   - tango-example: TANGO example device
#
# Requires: 
#   - tango.yml
#
version: "2.2"

services:
  tango-example:
    image: nexus.engageska-portugal.pt/tango-example/powersupply:latest
    container_name: ${CONTAINER_NAME_PREFIX}powersupply
    network_mode: ${NETWORK_MODE}
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --check-device test/power_supply/1 ||\
             tango_admin --add-server PowerSupply/test PowerSupply test/power_supply/1 &&\
             /venv/bin/python /app/powersupply/powersupply.py test"
