#
# Docker compose file for testing the TMC prototype in CI environment.
# The current setup provides one container each for Central Node, two Subarray Nodes
# in two separate containers, CspMasterLeafNode, SdpMasterLeafNode,
# four Dish Leaf Nodes in four separate containers, four Dish Masters in
# four separate containers, tmclogger, rsyslog service (for logging) and tmalarmhandler.
# Defines:
#   - rsyslog-tmcprototype: rsyslog service for logger
#   - dishmaster: Simulator of Dish Master device
#   - dishleafnode: Dish Leaf Node
#   - sdpsubarrayleafnode: SDP Subarray Leaf Node
#   - subarraynode: Subarray Node
#   - centralnode: Central Node
#   - cspmasterleafnode: CSP Master Leaf Node
#   - tmclogger: Logger for TMC
#   - tm-alarmhandler: TM AlarmHandler service
#   - configure-alarms: Alarm configuration for TM AlarmHandler
# Requires:
#   - tango-docker-compose.yml
#
# TODO: Some of the containers and part is commented out for future use
version: "2.2"
volumes:
  tangodb: {}

services:
  tmclogger:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/lmcbaseclasses:latest
    depends_on:
      - databaseds
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}logger
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python -u /app/skabase/SKALogger/SKALogger.py Ref -v4"

  dishmaster1:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 01 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishmaster2:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 02 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishmaster3:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 03 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishmaster4:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python -u /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 04 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode1:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster1
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_d0001/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 01 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode2:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster2
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_d0002/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 02 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode3:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster3
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode3
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_d0003/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 03 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  dishleafnode4:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishmaster4
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode4
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_d0004/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 04 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  cspsubarrayleafnode:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - cspsubarray
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspsubarrayleafnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_csp/elt/subarray01 10 &&\
             /venv/bin/python -u /app/tmcprototype/CspSubarrayLeafNode/CspSubarrayLeafNode/CspSubarrayLeafNode.py 01 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  cspmasterleafnode:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - cspmaster
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cspmasterleafnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_csp/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/CspMasterLeafNode/CspMasterLeafNode/CspMasterLeafNode.py 01 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  sdpsubarrayleafnode:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - sdpsubarray
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpsubarrayleafnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_sdp/elt/subarray_1 10 &&\
             /venv/bin/python -u /app/tmcprototype/SdpSubarrayLeafNode/SdpSubarrayLeafNode/SdpSubarrayLeafNode.py 01 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  sdpmasterleafnode:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - sdpmaster
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}sdpmasterleafnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device mid_sdp/elt/master 10 &&\
             /venv/bin/python -u /app/tmcprototype/SdpMasterLeafNode/SdpMasterLeafNode/SdpMasterLeafNode.py 01 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  subarraynode1:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - sdpsubarrayleafnode
      - cspsubarrayleafnode
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode1
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray01 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray01 10 &&\
             /venv/bin/python -u /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa1 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  subarraynode2:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - sdpsubarrayleafnode
      - cspsubarrayleafnode
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode2
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/csp_subarray01 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/sdp_subarray01 10 &&\
             /venv/bin/python -u /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa2 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  centralnode:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmcprototype:${TMC_VERSION}
    depends_on:
      - databaseds
      - rsyslog-tmcprototype
      - subarraynode1
      - subarraynode2
      - cspmasterleafnode
      - sdpmasterleafnode
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}centralnode
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/csp_master 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_leaf_node/sdp_master 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_subarray_node/1 10 &&\
             retry --max=5 -- tango_admin --ping-device ska_mid/tm_subarray_node/2 10 &&\
             /venv/bin/python -u /app/tmcprototype/CentralNode/CentralNode/CentralNode.py 01 -v4"
    volumes_from:
      - rsyslog-tmcprototype:rw

  rsyslog-tmcprototype:
    image: jumanjiman/rsyslog
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog
    network_mode: ${NETWORK_MODE}

  tm-alarmhandler:
    image: ${DOCKER_REGISTRY_HOST}/tango-example/tmalarmhandler
    depends_on:
      - databaseds
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmalarmhandler
    environment:
      - TANGO_HOST=${TANGO_HOST}
    init: true
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
            ./app/alarmhandler-srv 01 -v4"

