version: '2.2'

services:
  configure-devices:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}configure
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python /app/tmcprototype/configure.py"

  dishmaster1:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster1
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 01"
    volumes_from:
      - rsyslog-tmc:rw

  dishmaster2:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster2
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 02"
    volumes_from:
      - rsyslog-tmc:rw

  dishmaster3:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster3
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 03"
    volumes_from:
      - rsyslog-tmc:rw

  dishmaster4:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishmaster4
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             /venv/bin/python /app/tmcprototype/DishMaster/DishMaster/DishMaster.py 04"
    volumes_from:
      - rsyslog-tmc:rw

  dishleafnode1:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - dishmaster1
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode1
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 01"
    volumes_from:
      - rsyslog-tmc:rw

  dishleafnode2:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - dishmaster2
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode2
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 02"
    volumes_from:
      - rsyslog-tmc:rw

  dishleafnode3:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - dishmaster3
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode3
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 03"
    volumes_from:
      - rsyslog-tmc:rw

  dishleafnode4:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - dishmaster4
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}dishleafnode4
    init: true
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             /venv/bin/python /app/tmcprototype/DishLeafNode/DishLeafNode/DishLeafNode.py 04"
    volumes_from:
      - rsyslog-tmc:rw

  subarraynode1:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode1
    init: true
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa1"
    volumes_from:
    - rsyslog-tmc:rw

  subarraynode2:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - dishleafnode1
      - dishleafnode2
      - dishleafnode3
      - dishleafnode4
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}subarraynode2
    init: true
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             /venv/bin/python /app/tmcprototype/SubarrayNode/SubarrayNode/SubarrayNode.py sa2"
    volumes_from:
    - rsyslog-tmc:rw

  centralnode:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - databaseds
      - rsyslog-tmc
      - subarraynode1
      - subarraynode2
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}centralnode
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             sudo ln -sf /var/run/rsyslog/dev/log /dev/log &&\
             tango_admin --ping-device mid_d0001/elt/master 10 &&\
             tango_admin --ping-device mid_d0002/elt/master 10 &&\
             tango_admin --ping-device mid_d0003/elt/master 10 &&\
             tango_admin --ping-device mid_d0004/elt/master 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0001 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0002 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0003 10 &&\
             tango_admin --ping-device ska_mid/tm_leaf_node/d0004 10 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/1 10 &&\
             tango_admin --ping-device ska_mid/tm_subarray_node/2 10 &&\
             /venv/bin/python /app/tmcprototype/CentralNode/CentralNode/CentralNode.py 01"
    volumes_from:
    - rsyslog-tmc:rw

  tm-alarmhandler:
    image: nexus.engageska-portugal.pt/tango-example/tmalarmhandler:latest
    depends_on:
      - databaseds
      - configure-devices
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmalarmhandler
    init: true
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             ./app/alarmhandler-srv 01"

  configure-alarms:
    image: nexus.engageska-portugal.pt/tango-example/tmcprototype:latest
    depends_on:
      - tm-alarmhandler
      - dishmaster1
      - dishmaster2
      - dishmaster3
      - dishmaster4
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}configure-alarms
    init: true
    environment:
    - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             /venv/bin/python /app/tmcprototype/TMAlarmHandler/configure_alarms.py"

  rsyslog-tmc:
    image: jumanjiman/rsyslog
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog-tmc
    network_mode: ${NETWORK_MODE}
