version: "2.2"

services:
  webjivetestdevice:
    image: nexus.engageska-portugal.pt/tango-example/tango-example:webjive
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}webjivetestdevice
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=30 --strict --
             tango_admin --check-device test/webjivetestdevice/1 ||\
             tango_admin --add-server WebjiveTestDevice/test WebjiveTestDevice test/webjivetestdevice/1 &&\
             /venv/bin/python /app/WebjiveTestDevice/WebjiveTestDevice.py test"
